framework:
    router:
        # configure comment générer les URLs dans des contextes non-HTTP, comme les commandes CLI
        # voir https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        default_uri: '%env(DEFAULT_URI)%'

when@prod:
    framework:
        router:
            strict_requirements: null
